[package]
name = "boxstream"
version = "0.1.0"
authors = ["sean billig <sean.billig@gmail.com>"]
edition = "2018"
license = "AGPL-3.0"

[dependencies]
byteorder = "1.3"
futures-preview = "0.3.0-alpha.13"
quick-error = "1.2"
ssb-crypto = { git = "https://github.com/sunrise-choir/ssb-crypto", rev = "199a473" }
shs_core = { git = "https://github.com/sbillig/shs_core", rev = "5d8093c" }

[dev-dependencies]
async-ringbuffer = "0.4"
